### ISSUE TITLE
After build 4126 Spell Check and {/i}, {/b}, etc... are not working properly inside quotations

### ISSUE THREAD

**Issue by broliato** [koroshiya/Sublime-Renpy#10]
As the title says, after upragrading Sublime 4 to build version 4126 the integrated Spell Check is not working anymore on what is written inside quotations and all the closing tags for italic, bold, etc... are not being diferentiated, the opening ones are working properly.

**Comment by koroshiya** [comment]
It seems to be a problem with the Python syntax package. Even when going back to older builds of ST4 the problem still came up (I assume because syntax packages get updated independently from ST itself).
I've just uploaded a few patches and a new build (version 1.2.16) which appears to work around the issue for the time being.

**Comment by koroshiya** [comment]
Closing this issue as the "temporary workaround" has been in place for years and will probably remain there.
Relying on a bundled version of the Python syntax package seems to be the only way to guarantee compatibility irrespective of ST updates.
